<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions
		xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
		xmlns:tns="http://soapservice1.ahli.com/"
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		name="RandomQuoteService"
		targetNamespace="http://soapservice1.ahli.com/">
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
				   xmlns:tns="http://soapservice1.ahli.com/"
				   elementFormDefault="unqualified"
				   targetNamespace="http://soapservice1.ahli.com/" version="1.0">

			<xs:element name="getValue" type="tns:getValue"/>

			<xs:element name="getValueResponse"
						type="tns:getValueResponse"/>

			<xs:complexType name="getValue">
				<xs:sequence>
					<xs:element name="param1" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>

			<xs:complexType name="getValueResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="return" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>

		</xs:schema>
	</wsdl:types>
	<wsdl:message name="getValueResponse">
		<wsdl:part element="tns:getValueResponse" name="parameters">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="getValue">
		<wsdl:part element="tns:getValue" name="parameters">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="RandomQuote">
		<wsdl:operation name="getValue">
			<wsdl:input message="tns:getValue" name="getValue">
			</wsdl:input>
			<wsdl:output message="tns:getValueResponse"
						 name="getValueResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="RandomQuoteServiceSoapBinding"
				  type="tns:RandomQuote">
		<soap:binding style="document"
					  transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getValue">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="getValue">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getValueResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="RandomQuoteService">
		<wsdl:port binding="tns:RandomQuoteServiceSoapBinding"
				   name="RandomQuotePort">
			<soap:address
					location="http://localhost:8080/soapservice/services/quoteService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
